### ISSUE TITLE
Segmentation Fault while running scenario zero

### ISSUE THREAD

**Issue by aksyristos** [wineslab/o-ran-e2sim#2]
Hi, I'm trying out the operrangym ns-3 tutorial on a Ubuntu 22.04.1 LTS Virtualbox VM, and run into a SIGSEGV on the
./waf --run scratch/scenario-zero.cc
command

The error log is the following (with --gbd flag):
``Simulation time is 2 seconds 
[New Thread 0x7ffff249e640 (LWP 17271)]
[UNCON] Start E2 Agent (E2 Simulator)
[UNCON] Current Log level is 3
[INFO ] [SCTP] Binding client socket with source port 38471
[INFO ] [SCTP] Connecting to server at 10.0.2.10:36422 ...
[New Thread 0x7ffff1c9d640 (LWP 17272)]
[UNCON] Start E2 Agent (E2 Simulator)
[UNCON] Current Log level is 3
[INFO ] [SCTP] Binding client socket with source port 38472
[INFO ] [SCTP] Connecting to server at 10.0.2.10:36422 ...
[New Thread 0x7ffff149c640 (LWP 17273)]
[UNCON] Start E2 Agent (E2 Simulator)
[UNCON] Current Log level is 3
[INFO ] [SCTP] Binding client socket with source port 38473
[INFO ] [SCTP] Connecting to server at 10.0.2.10:36422 ...
[New Thread 0x7ffff0c9b640 (LWP 17274)]
[UNCON] Start E2 Agent (E2 Simulator)
[UNCON] Current Log level is 3
[INFO ] [SCTP] Binding client socket with source port 38474
[INFO ] [SCTP] Connecting to server at 10.0.2.10:36422 ...
[New Thread 0x7ffff049a640 (LWP 17275)]
[UNCON] Start E2 Agent (E2 Simulator)
[UNCON] Current Log level is 3
[INFO ] [SCTP] Binding client socket with source port 38475
[INFO ] [SCTP] Connecting to server at 10.0.2.10:36422 ...
[ERROR] [SCTP] Connection error: Connection timed out
[ERROR] [SCTP] Connection error: Connection timed out

Thread 1 "scenario-zero" received signal SIGSEGV, Segmentation fault.
0x00007ffff28f1594 in std::_Rb_tree_increment(std::_Rb_tree_node_base const*) () from /lib/x86_64-linux-gnu/libstdc++.so.6``

**Comment by Thecave3** [comment]
It looks that ns-O-RAN is not able to connect to the RIC. 
Did you check the IP address of the E2 Termination on the RIC side?

**Comment by Thecave3** [comment]
I close the issue untile further update w.r.t. the segmentation fault

**Comment by aksyristos** [comment]
Hi, sorry for the late reply

The RIC setup script prints as follows:
E2TERM_IP=10.0.2.10
E2TERM_SCTP_PORT=3422

which I presume are the correct ones
For all it's worth, I build the project from scratch on a physical Ubuntu 22.04 machine and it worked fine
