### ISSUE TITLE
Connection refused while running scenario zero

### ISSUE THREAD

**Issue by HuangLuchen** [wineslab/o-ran-e2sim#3]
Hi, I'm trying out the ns-o-ran tutorial on a Ubuntu 22.04.1.

```
./waf --run scratch/scenario-zero.cc
command
The error log is the following (with --gbd flag):
bufferSize 10 OutageThreshold -5 HandoverMode DynamicTtt e2TermIp 10.0.2.10 enableE2FileLogging 0
e2lteEnabled 1 e2nrEnabled 1 e2du 1 e2cuCp 1 e2cuUp 1 controlFilename  indicationPeriodicity 0.1
[INFO ] %%about to register e2sm func desc for 200

[INFO ] %%about to register callback for subscription for func_id 200
[INFO ] %%about to register e2sm func desc for 300

[INFO ] %%about to register callback for e2sm for func_id 300
+0.000000000s -1 MmWaveEnbNetDevice:SetE2Termination(): [DEBUG] Register E2SM
[INFO ] %%about to register e2sm func desc for 200

[INFO ] %%about to register callback for subscription for func_id 200
+0.000000000s -1 MmWaveEnbNetDevice:UpdateConfig(): [DEBUG] E2sim start in cell 2 force CSV logging 0
+0.000000000s -1 MmWaveEnbNetDevice:SetE2Termination(): [DEBUG] Register E2SM
[INFO ] %%about to register e2sm func desc for 200

[INFO ] %%about to register callback for subscription for func_id 200
+0.000000000s -1 MmWaveEnbNetDevice:UpdateConfig(): [DEBUG] E2sim start in cell 3 force CSV logging 0
+0.000000000s -1 MmWaveEnbNetDevice:SetE2Termination(): [DEBUG] Register E2SM
[INFO ] %%about to register e2sm func desc for 200

[INFO ] %%about to register callback for subscription for func_id 200
+0.000000000s -1 MmWaveEnbNetDevice:UpdateConfig(): [DEBUG] E2sim start in cell 4 force CSV logging 0
+0.000000000s -1 MmWaveEnbNetDevice:SetE2Termination(): [DEBUG] Register E2SM
[INFO ] %%about to register e2sm func desc for 200

[INFO ] %%about to register callback for subscription for func_id 200
+0.000000000s -1 MmWaveEnbNetDevice:UpdateConfig(): [DEBUG] E2sim start in cell 5 force CSV logging 0
Simulation time is 2 seconds 
[UNCON] Start E2 Agent (E2 Simulator)
[UNCON] Current Log level is 3
[INFO ] [SCTP] Binding client socket with source port 38471
[INFO ] [SCTP] Connecting to server at 10.0.2.10:36422 ...
[ERROR] [SCTP] Connection error: Connection refused
[UNCON] Start E2 Agent (E2 Simulator)
[UNCON] Current Log level is 3
[INFO ] [SCTP] Binding client socket with source port 38472
[INFO ] [SCTP] Connecting to server at 10.0.2.10:36422 ...
[ERROR] [SCTP] Connection error: Connection refused
assert failed. cond="m_ptr", msg="Attempted to dereference zero pointer", +0.000000000s -1 file=./ns3/ptr.h, line=630
terminate called without an active exception
```

**Comment by Thecave3** [comment]
Did you start the RIC and checked that the E2 RIC Termination is up and running?
Did you check the IP address of the E2 Termination on your machine?

**Comment by HuangLuchen** [comment]
> 

yes. they all running well, but i still got the mistake.

docker ps
CONTAINER ID   IMAGE                COMMAND                  CREATED              STATUS              PORTS                                                        NAMES
a6ec2f3b2f6f   sample-xapp:latest   "/bin/bash"              About a minute ago   Up 43 seconds                                                                    sample-xapp-24
45ab60c6cd58   e2term:bronze        "sh -c ./startup.sh"     About a minute ago   Up About a minute   0.0.0.0:36422->36422/sctp, :::36422->36422/sctp, 38000/tcp   e2term
bc76d4551f46   e2mgr:bronze         "sh -c './main  -por…"   About a minute ago   Up About a minute   3800/tcp                                                     e2mgr
5c7d277a0066   e2rtmansim:bronze    "/bin/sh -c 'exec ./…"   2 minutes ago        Up About a minute                                                                e2rtmansim
e83616316c68   dbaas:bronze         "redis-server"           2 minutes ago        Up 2 minutes        6379/tcp                                                     db

**Comment by HuangLuchen** [comment]
> Did you start the RIC and checked that the E2 RIC Termination is up and running? Did you check the IP address of the E2 Termination on your machine?
yes. they all running well, but i still got the mistake.

docker ps
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
a6ec2f3b2f6f sample-xapp:latest "/bin/bash" About a minute ago Up 43 seconds sample-xapp-24
45ab60c6cd58 e2term:bronze "sh -c ./startup.sh" About a minute ago Up About a minute 0.0.0.0:36422->36422/sctp, :::36422->36422/sctp, 38000/tcp e2term
bc76d4551f46 e2mgr:bronze "sh -c './main -por…" About a minute ago Up About a minute 3800/tcp e2mgr
5c7d277a0066 e2rtmansim:bronze "/bin/sh -c 'exec ./…" 2 minutes ago Up About a minute e2rtmansim
e83616316c68 dbaas:bronze "redis-server" 2 minutes ago Up 2 minutes 6379/tcp db

**Comment by HuangLuchen** [comment]
> Did you start the RIC and checked that the E2 RIC Termination is up and running? Did you check the IP address of the E2 Termination on your machine?

yes. they all running well, but i still got the mistake.
docker ps
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
a6ec2f3b2f6f sample-xapp:latest "/bin/bash" About a minute ago Up 43 seconds sample-xapp-24
45ab60c6cd58 e2term:bronze "sh -c ./startup.sh" About a minute ago Up About a minute 0.0.0.0:36422->36422/sctp, :::36422->36422/sctp, 38000/tcp e2term
bc76d4551f46 e2mgr:bronze "sh -c './main -por…" About a minute ago Up About a minute 3800/tcp e2mgr
5c7d277a0066 e2rtmansim:bronze "/bin/sh -c 'exec ./…" 2 minutes ago Up About a minute e2rtmansim
e83616316c68 dbaas:bronze "redis-server" 2 minutes ago Up 2 minutes 6379/tcp db

**Comment by HuangLuchen** [comment]
> Did you start the RIC and checked that the E2 RIC Termination is up and running? Did you check the IP address of the E2 Termination on your machine?

hi, i have rebuild the program in another system(ubuntu 22.04.6), this time i succeed. I think it depend on luck...

thank u for your reply! It's very fast ^ ^
