### ISSUE TITLE
Can ns-o-ran use in radio resource allocation and other place?

### ISSUE THREAD

**Issue by HuangLuchen** [wineslab/o-ran-e2sim#4]
HI Thecave3
    I am using the ns-o-ran for the first time, and I have read the ns-o-ran related papers. I am wonder if I can use the ns-o-ran to control RRC  and MAC layer to allocate radio resource to each user depend on the KMP? (In mmwave using TDMA, allocate the resource block). And can I use ns-o-ran to control the Protocol stack functions?  For example, can I  create two gNBs, one enables the PHY, MAC, RLC functions and disabled other functions. The other gNB  enables the RRC and PDCP functions and disabled other functions? In that way I have two nodes and I create the CU-DU separate on ns3.  Can ns-o-ran be used in these place?
    Thank you again, your replay will be very helpful!

**Comment by Thecave3** [comment]
Hi, this involves developing a new use case for ns-O-RAN, which is not a trivial task. please feel free to send an inquiry though email about it. I'll close the issue since it's not related to a bug on the E2sim fork
